### ISSUE TITLE
Events - errors and manual entry mods

### ISSUE THREAD

**Issue by ssmaxted** [simoncomputing/winventory#15]
When adding a new event on the Events page, if an error is made entering an event, upon retry, an error is generated.

The Events page also needs help from a usability standpoint - Integer Keys are not that user-friendly.  A type-ahead kind of entry could work.  Another idea is that on the Hardware page, we could have an Add Event button.  This could redirect to the Event page with the Hardware name already filled out.  This would serve the use case of needing to add information about physical repair, etc. to the hardware.

**Comment by mrigsbee** [comment]
After seeing an error when adding an event, you should be able to retry without getting an error, assuming the correct information is entered.

Working on type-ahead. This will work best for username, which is unique, but might cause problems with items such as hardware because, for instance, there could be many MacBook Pros and choosing which one to associate the event with could prove to be challenging.

**Comment by seamuslowry** [comment]
Added constraints to make Hardware Serial No. unique.  Is not currently followed.  Would need to flush database first, but no further serial numbers should match a previous one

**Comment by mrigsbee** [comment]
Associated users and locations have drop down menus now to make selection easier.

**Comment by seamuslowry** [comment]
using serial nos and license keys with typeaheads.  more user friendly
