### ISSUE TITLE
Reasonable date warnings

### ISSUE THREAD

**Issue by ssmaxted** [simoncomputing/winventory#5]
For dates on software page, is it a good idea to give warnings if date purchased is in the future, or if date of expiration is in the past?

For date on the hardware page, is it a good idea to give a warning if the date is in the future?

**Comment by seamuslowry** [comment]
Updated so cannot list a purchase date more than a week in the future, in either add or edit.  Listing expiration from past is currently still allowed just as a "you never know what you'll find" scenario.

**Comment by mrigsbee** [comment]
Kind of related -- we know that the date picker (the drop down calendar UI) would act strange if you tried typing the date in the input box, so I disabled that input so that the date picker UI ONLY will be used for picking dates. Right now this is only implemented for Hardware's insert page, but I plan on adding it to all other places where the date picker is used.

**Comment by chrismhess** [comment]
And they are all bounded within reasonable limits.
