### ISSUE TITLE
Hardware conditions

### ISSUE THREAD

**Issue by ssmaxted** [simoncomputing/winventory#7]
Only "good" is available as a condition in the drop down on the hardware entry page.

**Comment by chrismhess** [comment]
This is because the administrator is responsible for providing valid options for the users to specify for conditions. If you are an administrator signed in as username1, you can go to the gear icon on the top right and add or change those conditions so there are more options.

**Comment by woosanghun** [comment]
I would like to see the option filled with a recommended list of conditions when the system is initialized, rather than just have "good" as the seed for this field.   This would make it much more clear to users when  they start and most would use these values out of the box.  For those that customize, they can explore and customize.

**Comment by chrismhess** [comment]
Roger that, we will change it to reflect that functionality.
